# Generated by Django 2.2.6 on 2019-10-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
