# Generated by Django 2.2.6 on 2019-10-25 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='기사 ID', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='제목', max_length=255)),
                ('author', models.CharField(blank=True, help_text='기자이름', max_length=30, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_column='published_at', help_text='기사배포일자')),
                ('agency', models.CharField(help_text='언론사', max_length=30)),
                ('body', models.TextField(help_text='본문')),
            ],
            options={
                'db_table': 'Article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='이미지 ID', primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'db_table': 'ImageResource',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='강의 ID', primary_key=True, serialize=False)),
                ('episode', models.IntegerField(help_text='강의회차')),
                ('title', models.CharField(help_text='제목', max_length=255)),
                ('subtitle', models.CharField(help_text='부제목', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('article', models.ManyToManyField(related_name='lectures', to='lecture.Article')),
            ],
            options={
                'db_table': 'Lecture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='영상 ID', primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='동영상 url', max_length=255)),
                ('outline', models.TextField(help_text='강의개요')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('lecture', models.OneToOneField(help_text='강의 ID', on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
            ],
            options={
                'db_table': 'VideoLecture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='퀴즈 ID', primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='퀴즈내용', max_length=255)),
                ('number', models.IntegerField(help_text='퀴즈순서 번호')),
                ('choices', models.CharField(help_text='선택지', max_length=225)),
                ('hint', models.CharField(help_text='힌트', max_length=255)),
                ('answer', models.IntegerField(help_text='정답번호')),
                ('lecture', models.ForeignKey(help_text='강의 ID', on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
            ],
            options={
                'db_table': 'Quiz',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='금융상식 ID', primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='금융상식순서 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='lecture.Lecture')),
                ('thumbnail', models.ManyToManyField(related_name='knowledges', to='lecture.ImageResource')),
            ],
            options={
                'db_table': 'Knowledge',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ForeignKey(help_text='썸네일', on_delete=django.db.models.deletion.CASCADE, related_name='Articles', to='lecture.ImageResource'),
        ),
        migrations.CreateModel(
            name='LectureStatus',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='강의상태 ID', primary_key=True, serialize=False)),
                ('view_complete_sec', models.IntegerField(default=0, help_text='강의회차')),
                ('quiz_pass', models.BooleanField(db_column='quiz_pass', default=False, help_text='퀴즈 통과 여부')),
                ('video_pass', models.BooleanField(db_column='viewing_completion_pass', default=False, help_text='동영상 시청 완료 여부')),
                ('pass_date', models.DateTimeField(blank=True, db_column='pass_date', help_text='통과 완료일(동영상 + 퀴즈)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('lecture', models.ForeignKey(db_column='lecture_id', help_text='강의 ID', on_delete=django.db.models.deletion.CASCADE, related_name='lecture_status', to='lecture.Lecture')),
                ('user', models.ForeignKey(db_column='user_id', help_text='유저 ID', on_delete=django.db.models.deletion.CASCADE, related_name='lecture_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LectureStatus',
                'managed': True,
                'unique_together': {('user', 'lecture')},
            },
        ),
    ]
