# Generated by Django 2.2.6 on 2019-10-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20191030_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresource',
            name='image_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
